### ISSUE TITLE
initActivator with the type 'TY_QR' crashed app 

### ISSUE THREAD

**Issue by nono-la-frite** [Volst/tuyasmart-home-sdk-react-native#3]
Hi,

When i add device in EZ mode with initActivator (type 'TY_EZ') i have no problem but if i use the type 'TY_QR' (for camera) my app instant crashed.

Please find the logs below : 

```
01-21 10:41:14.317 16341 16341 E AndroidRuntime: FATAL EXCEPTION: main
01-21 10:41:14.317 16341 16341 E AndroidRuntime: Process:myPackage.debug, PID: 16341
01-21 10:41:14.317 16341 16341 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void com.tuya.smart.home.sdk.api.config.IConfig.start()' on a null object reference
01-21 10:41:14.317 16341 16341 E AndroidRuntime: 	at com.tuya.sdk.hardware.OooOooo.start(TuyaConnect.java:1)
01-21 10:41:14.317 16341 16341 E AndroidRuntime: 	at com.tuya.smart.rnsdk.activator.TuyaActivatorModule$initActivator$1.onSuccess(TuyaActivatorModule.kt:66)
01-21 10:41:14.317 16341 16341 E AndroidRuntime: 	at com.tuya.sdk.hardware.OooOoo$OooO00o.OooO0O0(TuyaActivator.java:4)
01-21 10:41:14.317 16341 16341 E AndroidRuntime: 	at com.tuya.sdk.hardware.OooOoo$OooO00o.onSuccess(TuyaActivator.java:1)
01-21 10:41:14.317 16341 16341 E AndroidRuntime: 	at com.tuya.smart.android.network.Business$RequestTask$3.run(Business.java:2)
01-21 10:41:14.317 16341 16341 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
01-21 10:41:14.317 16341 16341 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-21 10:41:14.317 16341 16341 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
01-21 10:41:14.317 16341 16341 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8107)
01-21 10:41:14.317 16341 16341 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-21 10:41:14.317 16341 16341 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
01-21 10:41:14.317 16341 16341 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

Any ideas ?
Regards

**Comment by nono-la-frite** [comment]
EDIT :
 When i searched on your code, maybe i found the problem.
In fact, on initActivator function you don't implement the  TuyaCameraActivatorBuilder (see https://developer.tuya.com/en/docs/app-development/android-app-sdk/wifinetwork?id=Ka6ki8lbwu82c#title-5-Camera%20scan%20code%20network%20configuration). Can you add this fonctionnality ? I have update your function and this correct the the problem but i block for resolve the Qrcode. The promise was never resolved. 
Of course my code is not the solution for accept multi type. It was only a test for get the Qrcode.

If you have any solution ? 

Best Regards

`
package com.tuya.smart.rnsdk.activator

import android.content.Intent
import android.provider.Settings
import android.util.Log
import com.facebook.react.bridge.*
import com.tuya.smart.android.common.utils.WiFiUtil
import com.tuya.smart.home.sdk.TuyaHomeSdk
import com.tuya.smart.home.sdk.builder.ActivatorBuilder
import com.tuya.smart.home.sdk.builder.TuyaCameraActivatorBuilder
import com.tuya.smart.rnsdk.utils.*
import com.tuya.smart.rnsdk.utils.Constant.HOMEID
import com.tuya.smart.rnsdk.utils.Constant.PASSWORD
import com.tuya.smart.rnsdk.utils.Constant.SSID
import com.tuya.smart.rnsdk.utils.Constant.TIME


import com.tuya.smart.sdk.api.ITuyaActivator
import com.tuya.smart.sdk.api.ITuyaCameraDevActivator
import com.tuya.smart.sdk.api.ITuyaSmartActivatorListener
import com.tuya.smart.sdk.api.ITuyaSmartCameraActivatorListener
import com.tuya.smart.sdk.bean.DeviceBean
import com.tuya.smart.sdk.enums.ActivatorModelEnum
import com.tuya.smart.sdk.api.ITuyaActivatorGetToken
import com.tuya.smart.home.sdk.builder.TuyaGwSubDevActivatorBuilder
import com.tuya.smart.rnsdk.utils.Constant.DEVID
import com.tuya.smart.rnsdk.utils.Constant.TYPE


class TuyaActivatorModule(reactContext: ReactApplicationContext) : ReactContextBaseJavaModule(reactContext) {

    var mTuyaActivator: ITuyaCameraDevActivator?=null
    var mITuyaActivator: ITuyaActivator?=null
    var mTuyaGWActivator: ITuyaActivator?=null
    override fun getName(): String {
        return "TuyaActivatorModule"
    }

    @ReactMethod
    fun getCurrentWifi(params: ReadableMap, successCallback: Callback,
                       errorCallback: Callback) {
        successCallback.invoke(WiFiUtil.getCurrentSSID(reactApplicationContext.applicationContext));
    }

    @ReactMethod
    fun openNetworkSettings(params: ReadableMap) {
        val currentActivity = currentActivity
        if (currentActivity == null) {
            return
        }
        try {
            currentActivity.startActivity(Intent(Settings.ACTION_SETTINGS))
        } catch (e: Exception) {
        }

    }

    @ReactMethod
    fun initActivator(params: ReadableMap, promise: Promise) {
        if (ReactParamsCheck.checkParams(arrayOf(HOMEID,SSID, PASSWORD,TIME,TYPE), params)){
            TuyaHomeSdk.getActivatorInstance().getActivatorToken(params.getDouble(HOMEID).toLong(),object : ITuyaActivatorGetToken {
                override fun onSuccess(token: String) {
                    mTuyaActivator= TuyaHomeSdk.getActivatorInstance().newCameraDevActivator(TuyaCameraActivatorBuilder()
                            .setSsid(params.getString(SSID))
                            .setContext(reactApplicationContext.applicationContext)
                            .setPassword(params.getString(PASSWORD))
//                            .setActivatorModel(ActivatorModelEnum.valueOf(params.getString(TYPE) as String))
                            .setTimeOut(params.getInt(TIME).toLong())
                            .setToken(token).setListener(getITuyaSmartCameraActivatorListener(promise)))
                    mTuyaActivator?.start()
                }


                override fun onFailure(s: String, s1: String) {
                    promise.reject(s,s1)
                }
            })
        }

    }

    /**
     * ZigBee子设备配网需要ZigBee网关设备云在线的情况下才能发起,且子设备处于配网状态。
     */
    @ReactMethod
    fun newGwSubDevActivator(params: ReadableMap,promise: Promise) {
        if (ReactParamsCheck.checkParams(arrayOf(DEVID,TIME), params)){
            val builder = TuyaGwSubDevActivatorBuilder()
                    //设置网关ID
                    .setDevId(params.getString(DEVID))
                    //设置配网超时时间
                    .setTimeOut(params.getInt(TIME).toLong())
                    .setListener(object : ITuyaSmartActivatorListener {
                        override fun onError(var1: String, var2: String) {
                            promise.reject(var1,var2)
                        }

                        /**
                         * 设备配网成功,且设备上线（手机可以直接控制），可以通过
                         */
                        override fun onActiveSuccess(var1: DeviceBean) {
                            promise.resolve(TuyaReactUtils.parseToWritableMap(var1))
                        }

                        /**
                         * device_find 发现设备
                        device_bind_success 设备绑定成功，但还未上线，此时设备处于离线状态，无法控制设备。
                         */
                        override fun onStep(var1: String, var2: Any) {
                           // promise.reject(var1,"")
                        }
                    })

            mTuyaGWActivator = TuyaHomeSdk.getActivatorInstance().newGwSubDevActivator(builder)
        }
    }

    @ReactMethod
    fun stopConfig() {
        mTuyaActivator?.stop()
        mITuyaActivator?.stop()
        mTuyaGWActivator?.stop()
    }
    @ReactMethod
    fun onDestory() {
        mTuyaActivator?.onDestroy()
        mITuyaActivator?.onDestroy()
        mTuyaGWActivator?.onDestroy()
    }

    fun getITuyaSmartActivatorListener(promise: Promise): ITuyaSmartActivatorListener {
        return object : ITuyaSmartActivatorListener {
            /**
             * 1001        网络错误
            1002        配网设备激活接口调用失败，接口调用不成功
            1003        配网设备激活失败，设备找不到。
            1004        token 获取失败
            1005        设备没有上线
            1006        配网超时
             */
            override fun onError(var1: String, var2: String) {
                promise.reject(var1,var2)
            }

            /**
             * 设备配网成功,且设备上线（手机可以直接控制），可以通过
             */
            override fun onActiveSuccess(var1: DeviceBean) {
                promise.resolve(TuyaReactUtils.parseToWritableMap(var1))
            }

            /**
             * device_find 发现设备
               device_bind_success 设备绑定成功，但还未上线，此时设备处于离线状态，无法控制设备。
             */
            override fun onStep(var1: String, var2: Any) {
                // IOS 没有onStep保持一致
                //promise.reject(var1,"")
            }
        }
    }
    fun getITuyaSmartCameraActivatorListener(promise: Promise): ITuyaSmartCameraActivatorListener {
        return object : ITuyaSmartCameraActivatorListener {
            /**
             * 1001        网络错误
            1002        配网设备激活接口调用失败，接口调用不成功
            1003        配网设备激活失败，设备找不到。
            1004        token 获取失败
            1005        设备没有上线
            1006        配网超时
             */
            override fun onError(var1: String, var2: String) {
                promise.reject(var1,var2)
            }

            /**
             * 设备配网成功,且设备上线（手机可以直接控制），可以通过
             */
            override fun onActiveSuccess(var1: DeviceBean) {
                promise.resolve(TuyaReactUtils.parseToWritableMap(var1))
            }

            /**
             * 设备配网成功,且设备上线（手机可以直接控制），可以通过
             */
            override fun onQRCodeSuccess(var1: String) {
                promise.resolve(var1)
            }

        }
    }
}
    
    
    `

**Comment by SpaceK33z** [comment]
Hey, I don't know, we only forked the repository from Tuya and made some changes. If you want any support you should contact them. This is the repository from Tuya: https://github.com/TuyaInc/tuyasmart-home-sdk-react-native

**Comment by nono-la-frite** [comment]
hi thank you for reply.

In fact, i've add the  mTuyaActivator?.createQRCode() function and it's works.

I'll answer you when I've put the code straight.

Regards

**Comment by bb441db** [comment]
Feel free to re-open is this is still an issue
